// Generated by the CFG AOT compiler. Do not edit.
//
// Memory is a sparse 8-way trie over the address bits.
//
// Why a trie: `S['memory'] & Record<Addr, V>` cannot work, because
// intersecting two different literals for one key gives `never` - the second
// write to a word poisons it, and an `i32.store8` is a read-modify-write, so
// four byte stores into one word are enough to lose the word.
//
// Why 8-way and not binary: the state has to come back to the host as text
// between chunks, and the type *printer* elides parts of deeply nested types
// (printing them as `any`) even when the type itself is perfectly correct.
// 5 levels stays clear of that, and it also costs 5 instantiations per
// read or write instead of 15.
import type { Wasm, WasmValue, Convert } from 'ts-type-math'

export type $Zero = ['00000000000000000000000000000000']
/// A node is always a tuple: [word] is a leaf, a 8-tuple is a branch.
/// Deliberately not a union - a union constraint makes `infer M extends $Node`
/// distribute, and a write against a distributed memory silently returns two
/// copies of the trie unioned together.
export type $Node = unknown[]

/// The state a block's instruction pipeline threads through: memory in slot 0,
/// then one slot per value. Typing it this way means a step can read `$S[3]` and
/// get a `WasmValue` back with no narrowing at the read.
export type $State = [$Node, ...WasmValue[]]

/// everything but the memory slot, so a store can put a new memory in its place
export type $Rest<$S extends $State> =
  $S extends [unknown, ...infer $R extends WasmValue[]] ? $R : never
/// Fuel is a string of '1's, one per unit of work. Decrementing takes a prefix
/// off a string, which costs nothing; the obvious `[any, ...infer Rest]` tuple
/// copies every remaining element on every hop instead, and at a few thousand
/// units that dominated the whole frame.
export type $Fuel = string

/// the addressing bits of an address: drop the two byte-offset bits, keep 15
export type $Slice<A extends string> =
  A extends `${infer _h0}${infer _h1}${infer _h2}${infer _h3}${infer _h4}${infer _h5}${infer _h6}${infer _h7}${infer _h8}${infer _h9}${infer _h10}${infer _h11}${infer _h12}${infer _h13}${infer _h14}${infer b0}${infer b1}${infer b2}${infer b3}${infer b4}${infer b5}${infer b6}${infer b7}${infer b8}${infer b9}${infer b10}${infer b11}${infer b12}${infer b13}${infer b14}${infer _l0}${infer _l1}`
    ? `${b0}${b1}${b2}${b3}${b4}${b5}${b6}${b7}${b8}${b9}${b10}${b11}${b12}${b13}${b14}`
    : never

export type $Word<T> = T extends [infer W extends string] ? W : '00000000000000000000000000000000'

/// pick child D of a branch node
export type $Sel<T extends unknown[], D extends string> =
  D extends '000' ? T[0] :
  D extends '001' ? T[1] :
  D extends '010' ? T[2] :
  D extends '011' ? T[3] :
  D extends '100' ? T[4] :
  D extends '101' ? T[5] :
  D extends '110' ? T[6] :
  D extends '111' ? T[7] :
  never

/// replace child D of a branch node with X
export type $Set<T extends unknown[], D extends string, X> =
  D extends '000' ? [X, T[1], T[2], T[3], T[4], T[5], T[6], T[7]] :
  D extends '001' ? [T[0], X, T[2], T[3], T[4], T[5], T[6], T[7]] :
  D extends '010' ? [T[0], T[1], X, T[3], T[4], T[5], T[6], T[7]] :
  D extends '011' ? [T[0], T[1], T[2], X, T[4], T[5], T[6], T[7]] :
  D extends '100' ? [T[0], T[1], T[2], T[3], X, T[5], T[6], T[7]] :
  D extends '101' ? [T[0], T[1], T[2], T[3], T[4], X, T[6], T[7]] :
  D extends '110' ? [T[0], T[1], T[2], T[3], T[4], T[5], X, T[7]] :
  D extends '111' ? [T[0], T[1], T[2], T[3], T[4], T[5], T[6], X] :
  never

export type $Get<T, B extends string> =
  B extends `${infer d0}${infer d1}${infer d2}${infer Rest}`
    ? T extends [infer c0, infer c1, infer c2, infer c3, infer c4, infer c5, infer c6, infer c7]
      ? $Get<$Sel<[c0, c1, c2, c3, c4, c5, c6, c7], `${d0}${d1}${d2}`>, Rest>
      : $Word<T>
    : $Word<T>

/// Writing into a leaf that stands for a whole subtree splits it, and every
/// child inherits the leaf: a leaf above the bottom means "every word below me
/// holds this", which is how all-zero subtrees stay shared and cheap.
export type $Put<T, B extends string, V extends string> =
  B extends `${infer d0}${infer d1}${infer d2}${infer Rest}`
    ? T extends [infer c0, infer c1, infer c2, infer c3, infer c4, infer c5, infer c6, infer c7]
      ? $Set<[c0, c1, c2, c3, c4, c5, c6, c7], `${d0}${d1}${d2}`, $Put<$Sel<[c0, c1, c2, c3, c4, c5, c6, c7], `${d0}${d1}${d2}`>, Rest, V>>
      : $Set<[T, T, T, T, T, T, T, T], `${d0}${d1}${d2}`, $Put<T, Rest, V>>
    : [V]

/// Writing a byte is a read, a splice and a write, which is two walks down the
/// trie for one pixel. This is the same descent as `$Put`, except that the leaf
/// it lands on is spliced rather than replaced, so a byte store costs one walk.
export type $PutByte<T, B extends string, O extends string, V extends string> =
  B extends `${infer d0}${infer d1}${infer d2}${infer Rest}`
    ? T extends [infer c0, infer c1, infer c2, infer c3, infer c4, infer c5, infer c6, infer c7]
      ? $Set<[c0, c1, c2, c3, c4, c5, c6, c7], `${d0}${d1}${d2}`, $PutByte<$Sel<[c0, c1, c2, c3, c4, c5, c6, c7], `${d0}${d1}${d2}`>, Rest, O, V>>
      : $Set<[T, T, T, T, T, T, T, T], `${d0}${d1}${d2}`, $PutByte<T, Rest, O, V>>
    : [$SetByte<$Word<T>, O, V>]

export type $AlignAddr<A extends WasmValue> = Wasm.I32And<A, '11111111111111111111111111111100'>

/// The two low bits of an address, as characters. A byte offset is the last two
/// characters of the address string - no arithmetic needed to find it.
export type $Off<A extends string> =
  A extends `${infer a0}${infer a1}${infer a2}${infer a3}${infer a4}${infer a5}${infer a6}${infer a7}${infer a8}${infer a9}${infer a10}${infer a11}${infer a12}${infer a13}${infer a14}${infer a15}${infer a16}${infer a17}${infer a18}${infer a19}${infer a20}${infer a21}${infer a22}${infer a23}${infer a24}${infer a25}${infer a26}${infer a27}${infer a28}${infer a29}${infer a30}${infer a31}` ? `${a30}${a31}` : never

/// Read one byte out of a word by slicing characters, not by shifting bits.
/// Words are little-endian, so byte 0 is the *last* eight characters.
export type $GetByte<W extends string, O extends string> =
  W extends `${infer w0}${infer w1}${infer w2}${infer w3}${infer w4}${infer w5}${infer w6}${infer w7}${infer w8}${infer w9}${infer w10}${infer w11}${infer w12}${infer w13}${infer w14}${infer w15}${infer w16}${infer w17}${infer w18}${infer w19}${infer w20}${infer w21}${infer w22}${infer w23}${infer w24}${infer w25}${infer w26}${infer w27}${infer w28}${infer w29}${infer w30}${infer w31}`
    ? O extends '00' ? `000000000000000000000000${w24}${w25}${w26}${w27}${w28}${w29}${w30}${w31}`
      : O extends '01' ? `000000000000000000000000${w16}${w17}${w18}${w19}${w20}${w21}${w22}${w23}`
      : O extends '10' ? `000000000000000000000000${w8}${w9}${w10}${w11}${w12}${w13}${w14}${w15}`
      : `000000000000000000000000${w0}${w1}${w2}${w3}${w4}${w5}${w6}${w7}`
    : never

/// Replace one byte of a word with the low byte of V, again by slicing.
export type $SetByte<W extends string, O extends string, V extends string> =
  W extends `${infer w0}${infer w1}${infer w2}${infer w3}${infer w4}${infer w5}${infer w6}${infer w7}${infer w8}${infer w9}${infer w10}${infer w11}${infer w12}${infer w13}${infer w14}${infer w15}${infer w16}${infer w17}${infer w18}${infer w19}${infer w20}${infer w21}${infer w22}${infer w23}${infer w24}${infer w25}${infer w26}${infer w27}${infer w28}${infer w29}${infer w30}${infer w31}`
    ? V extends `${infer v0}${infer v1}${infer v2}${infer v3}${infer v4}${infer v5}${infer v6}${infer v7}${infer v8}${infer v9}${infer v10}${infer v11}${infer v12}${infer v13}${infer v14}${infer v15}${infer v16}${infer v17}${infer v18}${infer v19}${infer v20}${infer v21}${infer v22}${infer v23}${infer v24}${infer v25}${infer v26}${infer v27}${infer v28}${infer v29}${infer v30}${infer v31}`
      ? O extends '00' ? `${w0}${w1}${w2}${w3}${w4}${w5}${w6}${w7}${w8}${w9}${w10}${w11}${w12}${w13}${w14}${w15}${w16}${w17}${w18}${w19}${w20}${w21}${w22}${w23}${v24}${v25}${v26}${v27}${v28}${v29}${v30}${v31}`
        : O extends '01' ? `${w0}${w1}${w2}${w3}${w4}${w5}${w6}${w7}${w8}${w9}${w10}${w11}${w12}${w13}${w14}${w15}${v24}${v25}${v26}${v27}${v28}${v29}${v30}${v31}${w24}${w25}${w26}${w27}${w28}${w29}${w30}${w31}`
        : O extends '10' ? `${w0}${w1}${w2}${w3}${w4}${w5}${w6}${w7}${v24}${v25}${v26}${v27}${v28}${v29}${v30}${v31}${w16}${w17}${w18}${w19}${w20}${w21}${w22}${w23}${w24}${w25}${w26}${w27}${w28}${w29}${w30}${w31}`
        : `${v24}${v25}${v26}${v27}${v28}${v29}${v30}${v31}${w8}${w9}${w10}${w11}${w12}${w13}${w14}${w15}${w16}${w17}${w18}${w19}${w20}${w21}${w22}${w23}${w24}${w25}${w26}${w27}${w28}${w29}${w30}${w31}`
      : never
    : never

export type $ByteOffset<A extends WasmValue> = Wasm.I32And<A, '00000000000000000000000000000011'>

export type $Read<M extends $Node, A extends WasmValue> = $Get<M, $Slice<A>>
export type $Write<M extends $Node, A extends WasmValue, V extends WasmValue> = $Put<M, $Slice<A>, V>

/// 8-bit access: one trie walk plus one character splice, no arithmetic at all
export type $Load8U<M extends $Node, A extends WasmValue> = $GetByte<$Read<M, A>, $Off<A>>
export type $Load8S<M extends $Node, A extends WasmValue> =
  Wasm.I32ShrS<Wasm.I32Shl<$Load8U<M, A>, '00000000000000000000000000011000'>, '00000000000000000000000000011000'>
export type $Store8<M extends $Node, A extends WasmValue, V extends WasmValue> =
  $PutByte<M, $Slice<A>, $Off<A>, V>

/// 32-bit access: aligned is a plain trie read or write; unaligned falls back to
/// the bit arithmetic, which pong never needs
export type $Load32<M extends $Node, A extends WasmValue> =
  $Off<A> extends '00'
    ? $Read<M, A>
    : Wasm.I32Or<
        Wasm.I32ShrU<$Read<M, A>, Wasm.I32Shl<$ByteOffset<A>, '00000000000000000000000000000011'>>,
        Wasm.I32Shl<$Read<M, Wasm.I32Add<$AlignAddr<A>, '00000000000000000000000000000100'>>, Wasm.I32Sub<'00000000000000000000000000100000', Wasm.I32Shl<$ByteOffset<A>, '00000000000000000000000000000011'>>>
      >
export type $Store32<M extends $Node, A extends WasmValue, V extends WasmValue> =
  $Off<A> extends '00'
    ? $Write<M, A, V>
    : $Store16<$Store16<M, A, V>, Wasm.I32Add<A, '00000000000000000000000000000010'>, Wasm.I32ShrU<V, '00000000000000000000000000010000'>>

/// 16-bit access: two byte splices when it stays inside a word
export type $Load16U<M extends $Node, A extends WasmValue> =
  $Off<A> extends '11'
    ? Wasm.I32Or<
        Wasm.I32ShrU<$Read<M, A>, '00000000000000000000000000011000'>,
        Wasm.I32Shl<Wasm.I32And<$Read<M, Wasm.I32Add<$AlignAddr<A>, '00000000000000000000000000000100'>>, '00000000000000000000000011111111'>, '00000000000000000000000000001000'>
      >
    : Wasm.I32Or<$Load8U<M, A>, Wasm.I32Shl<$GetByte<$Read<M, A>, $Next<$Off<A>>>, '00000000000000000000000000001000'>>
export type $Load16S<M extends $Node, A extends WasmValue> =
  Wasm.I32ShrS<Wasm.I32Shl<$Load16U<M, A>, '00000000000000000000000000010000'>, '00000000000000000000000000010000'>
export type $Next<O extends string> = O extends '00' ? '01' : O extends '01' ? '10' : O extends '10' ? '11' : '00'
export type $Store16<M extends $Node, A extends WasmValue, V extends WasmValue> =
  $Off<A> extends '11'
    ? $Store8<$Store8<M, A, V>, Wasm.I32Add<A, '00000000000000000000000000000001'>, Wasm.I32ShrU<V, '00000000000000000000000000001000'>>
    : $Write<M, A, $SetByte<$SetByte<$Read<M, A>, $Off<A>, V>, $Next<$Off<A>>, Wasm.I32ShrU<V, '00000000000000000000000000001000'>>>

export type $ToNumber<V> = Convert.WasmValue.ToTSNumber<V & string, 'i32'>

export type $Flip = { '0': '1', '1': '0' }

/// logical not of a wasm boolean (0 or 1)
export type $Not1<B extends string> =
  B extends '00000000000000000000000000000000' ? '00000000000000000000000000000001' : '00000000000000000000000000000000'

/// equality is type identity: no bit walking, no pattern match
export type $Eq<A extends string, B extends string> =
  A extends B ? '00000000000000000000000000000001' : '00000000000000000000000000000000'
export type $Ne<A extends string, B extends string> =
  A extends B ? '00000000000000000000000000000000' : '00000000000000000000000000000001'


export type $InitialMemory = $Zero

export type $b0_0<$F extends string, $M extends $Node, $l0 extends WasmValue, $l1 extends WasmValue> =
  $F extends `1${infer $F1}`
  ? Wasm.I32Xor<$l0, $l1> extends infer $t0 extends WasmValue
    ? ['r', $M, $t0]
    : never
  : ['s', '0_0', $M, $l0, $l1]


export type $entry<$F extends string, $M extends $Node, $p0 extends WasmValue, $p1 extends WasmValue> =
  $b0_0<$F, $M, $p0, $p1>
