(module
  (type $t0 (func))
  (type $t1 (func (result i32)))
  (func $__wasm_call_ctors (export "__wasm_call_ctors") (type $t0))
  (func $entry (export "entry") (type $t1) (result i32)
    (i32.const 1024))
  (memory $memory (export "memory") 2)
  (global $__dso_handle (export "__dso_handle") i32 (i32.const 1024))
  (global $__data_end (export "__data_end") i32 (i32.const 1231))
  (global $__stack_low (export "__stack_low") i32 (i32.const 1232))
  (global $__stack_high (export "__stack_high") i32 (i32.const 66768))
  (global $__global_base (export "__global_base") i32 (i32.const 1024))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66768))
  (global $__heap_end (export "__heap_end") i32 (i32.const 131072))
  (global $__memory_base (export "__memory_base") i32 (i32.const 0))
  (global $__table_base (export "__table_base") i32 (i32.const 1))
  (data $d0 (i32.const 1024) "Greetings humans, I am Ziltoid... the omniscient.\0aI have come far from across the Omniverse.\0aYou shall fetch me your universe's ultimate cup of coffee... Black!\0aYou have five Earth minutes.\0aMake it perfect!"))
